# Numpy

It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
In NumPy dimensions are called axes. The number of axes is rank.
NumPy’s array class is called ndarray. It is also known by the alias array.

# 1.array creation

In [1]:
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [8]:
a = np.array([[1,2,3],[4,5,6]], dtype='float') #Creating array from list with type float
print ("Array created using passed list:\n", a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [10]:
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [11]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
       "Array type is complex:\n", d)


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [13]:
# Create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)


A random array:
 [[0.17445387 0.7140525 ]
 [0.34713819 0.35248694]]


In [14]:
# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [15]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g)


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [18]:
#Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
 
newarr = arr.reshape(2, 2, 3)
 
print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [17]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
 
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# 2.array indexing

For analysing and manipulating array object

   Slicing  ~  specify a slice for each dimension of the array.                               
   Boolean Array Indexing ~  lists are passed for indexing for each dimension.
   Integer Array Indexing ~  want to pick elements from array which satisfy some condition.

In [19]:
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [20]:
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [21]:
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [22]:
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# 3. Basic operations

Operations on single array: We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the existing array is modified.

In [23]:
a = np.array([1, 2, 5, 3])
 
# add 1 to every element
print ("Adding 1 to every element:", a+1)
 
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
 
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
 
# square each element
print ("Squaring each element:", a**2)
 
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
 
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


Unary operators: provid as a method of ndarray class. Includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

In [24]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
 
# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))
 
# minimum element of array
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))
 
# sum of array elements
print ("Sum of all array elements:",
                            arr.sum())
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


Binary operators: Use all basic arithmetic operators like +, -, /, , etc. 
In case of +=, -=, = operators, the existing array is modified.

In [25]:
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])
 
# add arrays
print ("Array sum:\n", a + b)
 
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
 
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


Universal functions (ufunc): NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

Note: Operations using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc

In [26]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
 
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
 
# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


# 4. Sorting array

In [27]:
a = np.array([[1, 4, 2],
                 [3, 4, 6],
              [0, -1, 5]])
 
# sorted array
print ("Array elements in sorted order:\n",
                    np.sort(a, axis = None))
 
# sort array row-wise
print ("Row-wise sorted array:\n",
                np.sort(a, axis = 1))
 
# specify sort algorithm
print ("Column wise sort by applying merge-sort:\n",
            np.sort(a, axis = 0, kind = 'mergesort'))
 
# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
 
# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
            
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
             
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


### Initialize a NumPy array from a list.

In [28]:
li = [1, 2, 3, 4]
numpyArr = np.array(li)
print(numpyArr)

[1 2 3 4]


In [29]:
print("li =", li, "and type(li) =", type(li))
print("numpyArr =", numpyArr, "and type(numpyArr) =", type(numpyArr))

li = [1, 2, 3, 4] and type(li) = <class 'list'>
numpyArr = [1 2 3 4] and type(numpyArr) = <class 'numpy.ndarray'>


###  initialize NumPy array from a tuple
Tuple is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Set, and Dictionary, all with different qualities and usage. A tuple is a collection which is ordered and unchangeable. Tuples are written with round brackets.

In [30]:
tup = (1, 2, 3, 4)
numpyArr = np.array(tup)
  
print("tup =", tup, "and type(tup) =", type(tup))
print("numpyArr =", numpyArr, "and type(numpyArr) =", type(numpyArr))

tup = (1, 2, 3, 4) and type(tup) = <class 'tuple'>
numpyArr = [1 2 3 4] and type(numpyArr) = <class 'numpy.ndarray'>


## Multi dimentional array
Type of array

In [31]:
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
 
# creating numpy array
sample_array = np.array([list_1,
                         list_2,
                         list_3])
 
print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Note: use [ ] operators inside numpy.array() for multi-dimensional

## Anatomy of an array :
1. Axis: The Axis of an array describes the order of the indexing into the array.

Axis 0 = one dimensional

Axis 1 = Two dimensional

Axis 2 = Three dimensional 

2. Shape: The number of elements along with each axis. It is from a tuple.
3. Rank: The rank of an array is simply the number of axes (or dimensions) it has.
4. Data type objects (dtype): Data type objects (dtype) is an instance of numpy.dtype class. It describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted.

In [32]:
# Creating the array
sample_array_1 = np.array([[0, 4, 2]])
 
sample_array_2 = np.array([0.2, 0.4, 2.4])
 
# display data type
print("Data type of the array 1 :",
      sample_array_1.dtype)
 
print("Data type of array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int32
Data type of array 2 : float64


## Some different way of creating Numpy Array :


1. numpy.array(): The Numpy array object in Numpy is called ndarray. We can create ndarray using numpy.array() function.

Syntax: numpy.array(parameter)

In [33]:
arr = np.array([3,4,5,5])
 
print("Array :",arr)

Array : [3 4 5 5]


2. numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.

Syntax: numpy.fromiter(iterable, dtype, count=-1)

In [36]:
# iterable
iterable = (a*a for a in range(8))
 
arr = np.fromiter(iterable, float)
 
print("fromiter() array :",arr)
var = "Aditi&Aastha"
 
arr = np.fromiter(var, dtype = 'U2')
 
print("fromiter() array :",
      arr)

fromiter() array : [ 0.  1.  4.  9. 16. 25. 36. 49.]
fromiter() array : ['A' 'd' 'i' 't' 'i' '&' 'A' 'a' 's' 't' 'h' 'a']


3. numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.

Syntax: numpy.arange([start, ]stop, [step, ]dtype=None)

In [37]:
np.arange(1, 20 , 2,
          dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

4. numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits. 

Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [38]:
np.linspace(3.5, 10, 3)

array([ 3.5 ,  6.75, 10.  ])

In [39]:
np.linspace(3.5, 10, 3,
            dtype = np.int32)

array([ 3,  6, 10])

5. numpy.empty(): This function create a new array of given shape and type, without initializing value.

Syntax: numpy.empty(shape, dtype=float, order=’C’)

In [40]:
np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[1, 5, 1],
       [2, 2, 2],
       [3, 4, 0],
       [4, 2, 1]])

6. numpy.ones(): This function is used to get a new array of given shape and type, filled with ones(1).

Syntax: numpy.ones(shape, dtype=None, order=’C’)

In [41]:
np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

7. numpy.zeros(): This function is used to get a new array of given shape and type, filled with zeros(0). 

Syntax: numpy.ones(shape, dtype=None)

In [42]:
np.zeros([4, 3],
         dtype = np.int32,
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

REMINDER: "int32 is an integer between -2^31 and 2^31 - 1. This range requires 32 bits of memory, and hence the name. Numpy allows for a variety of data types that are not present in regular Python, whose int type can be really, really large. Moreover, unlike Python's list, all elements of a Numpy array must be of the same type."

# Comparison between Numpy array and Python List

### Memory consumption between Numpy array and lists 
In this example, a Python list and a Numpy array of size 1000 will be created. The size of each element and then the whole size of both containers will be calculated and a comparison will be done in terms of memory consumption. 

In [43]:
# importing numpy package
import numpy as np

# importing system module
import sys

# declaring a list of 1000 elements
S= range(1000)

# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(S))

# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))

# declaring a Numpy array of 1000 elements
D= np.arange(1000)

# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)

# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)


Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  4000


### Time comparison between Numpy array and Python lists 
In this example, 2 Python lists and 2 Numpy arrays will be created and each container has 1000000 elements. Multiplication of elements in both the lists and Numpy arrays respectively will be carried out and the difference in time needed for the execution for both the containers will be analyzed to determine which one takes less time to perform the operation.

In [44]:
# importing required packages
import numpy
import time

# size of arrays and lists
size = 1000000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# capturing time before the multiplication of Python lists
initialTime = time.time()

# multiplying elements of both the lists and stored in another list
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists to perform multiplication:",(time.time() - initialTime),"seconds")

# capturing time before the multiplication of Numpy arrays
initialTime = time.time()

# multiplying elements of both the Numpy arrays and stored in another Numpy array
resultantArray = array1 * array2

# calculating execution time
print("Time taken by NumPy Arrays to perform multiplication:",
    (time.time() - initialTime),"seconds")


Time taken by Lists to perform multiplication: 0.34104418754577637 seconds
Time taken by NumPy Arrays to perform multiplication: 0.0 seconds


### Effect of operations on Numpy array and Python Lists 
In this example, the incapability of the Python list to carry out a basic operation is demonstrated. A Python list and a Numpy array having the same elements will be declared and an integer will be added to increment each element of the container by that integer value without looping statements. The effect of this operation on the Numpy array and Python list will be analyzed.

In [45]:
# importing Numpy package
import numpy as np

# declaring a list
ls =[1, 2, 3]

# converting the list into a Numpy array
arr = np.array(ls)

try:
   # adding 4 to each element of list
    ls = ls + 4

except(TypeError):
    print("Lists don't support list + int")

# now on array
try:
    # adding 4 to each element of Numpy array
    arr = arr + 4

    # printing the Numpy array
    print("Modified Numpy array: ",arr)

except(TypeError):
    print("Numpy arrays don't support list + int")
import numpy as np
  
# declaring a list
ls =[1, 2, 3]
  
# converting the list into a Numpy array
arr = np.array(ls)
  
try:
    # adding 4 to each element of list
    ls = ls + 4
      
except(TypeError):
    print("Lists don't support list + int")
  
# now on array
try:
    # adding 4 to each element of Numpy array
    arr = arr + 4
  
    # printing the Numpy array
    print("Modified Numpy array: ",arr)
      
except(TypeError):
    print("Numpy arrays don't support list + int")

Lists don't support list + int
Modified Numpy array:  [5 6 7]


##### Conclusion
Advantages of using Numpy Arrays Over Python Lists:

Consumes less memory.
Fast as compared to the python List.
Convenient to use.


## How to generate 2-D Gaussian array using NumPy?

# Numpy Array Manipulation

## Copy & View

(No Copy by Assigning)

In [48]:
# creating array
arr = np.array([2, 4, 6, 8, 10])
  
# assigning arr to nc
nc = arr
  
# both arr and nc have same id
print("id of arr", id(arr))
print("id of nc", id(nc))
  
# updating nc
nc[0]= 12
  
# printing the values
print("original array- ", arr)
print("assigned array- ", nc)

id of arr 2470076921296
id of nc 2470076921296
original array-  [12  4  6  8 10]
assigned array-  [12  4  6  8 10]


View: This is also known as Shallow Copy. The view is just a view of the original array and view does not own the data. When we make changes to the view it affects the original array, and when changes are made to the original array it affects the view.

making a view and changing original array

In [49]:
arr = np.array([2, 4, 6, 8, 10])
  
# creating view 
v = arr.view()
  
# both arr and v have different id
print("id of arr", id(arr))
print("id of v", id(v))
  
# changing original array
# will effect view
arr[0] = 12
  
# printing array and view
print("original array- ", arr)
print("view- ", v)

id of arr 2470076921776
id of v 2470076919952
original array-  [12  4  6  8 10]
view-  [12  4  6  8 10]


Copy: This is also known as Deep Copy. The copy is completely a new array and copy owns the data. When we make changes to the copy it does not affect the original array, and when changes are made to the original array it does not affect the copy.

Example: (making a copy and changing original array)

In [50]:
# creating array
arr = np.array([2, 4, 6, 8, 10])
  
# creating copy of array
c = arr.copy()
  
# both arr and c have different id
print("id of arr", id(arr))
print("id of c", id(c))
  
# changing original array
# this will not effect copy
arr[0] = 12
  
# printing array and copy
print("original array- ", arr)
print("copy- ", c)

id of arr 2470076922544
id of c 2470076920240
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


Array Owning it’s Data:
To check whether array own it’s data in view and copy we can use the fact that every NumPy array has the attribute base that returns None if the array owns the data. Else, the base attribute refers to the original object.

In [51]:
# creating array
arr = np.array([2, 4, 6, 8, 10])
  
# creating copy of array
c = arr.copy()
  
# creating view of array
v = arr.view()
  
# printing base attribute of copy and view
print(c.base)
print(v.base)

None
[ 2  4  6  8 10]


### Appending values at the end of an NumPy array

1.Appending a single value to a 1D array.
2.Appending another array at the end of a 1D array
3.Appending values at the end of the n-dimensional array
  - Lets take example of last one

In [52]:
# create an array
arr = np.arange(1, 13).reshape(2, 6)
print('Original Array')
print(arr, '\n')
 
# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
print('Array to be appended column wise')
print(col)
arr_col = np.append(arr, col, axis=0)
print('Array after appending the values column wise')
print(arr_col, '\n')
 
# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
print('Array to be appended row wise')
print(row)
arr_row = np.append(arr, row, axis=1)
print('Array after appending the values row wise')
print(arr_row)

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

Array to be appended column wise
[[ 5  6  7  8  9 10]]
Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

Array to be appended row wise
[[1]
 [2]]
Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


### How to swap columns of a given NumPy array?

Approach :

Import NumPy module
Create a NumPy array
Swap the column with Index
Print the Final array

Swapping the column of an array. 

In [53]:
# creating array with shape(4,3)
my_array = np.arange(12).reshape(4, 3)
print("Original array:")
print(my_array)
 
# swapping the column with index of
# original array
my_array[:, [2, 0]] = my_array[:, [0, 2]]
print("After swapping arrays the last column and first column:")
print(my_array)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping arrays the last column and first column:
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


Example 2: Swapping the column of an array with the user chooses.

In [54]:
# Creating array
my_array = np.arange(12).reshape(4, 3)
print("Original Array : ")
print(my_array)
# creating function for swap
 
def Swap(arr, start_index, last_index):
    arr[:, [start_index, last_index]] = arr[:, [last_index, start_index]]
 
# passing parameter into the function
Swap(my_array, 0, 1)
print(" After Swapping :")
print(my_array)

Original Array : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 After Swapping :
[[ 1  0  2]
 [ 4  3  5]
 [ 7  6  8]
 [10  9 11]]


## Insert a new axis within a NumPy array

Method 1: Using numpy.newaxis()
The first method is to use numpy.newaxis object. This object is equivalent to use None as a parameter while declaring the array. The trick is to use the numpy.newaxis object as a parameter at the index location in which you want to add the new axis.
Example: 

In [55]:
arr = np.arange(5*5).reshape(5, 5)
print(arr.shape)
  
# promoting 2D array to a 5D array
# arr[None, ..., None, None]
arr_5D = arr[np.newaxis, ..., np.newaxis, np.newaxis]
  
print(arr_5D.shape)

(5, 5)
(1, 5, 5, 1, 1)


Method 2: Using numpy.expand_dims()

The second method is to use numpy.expand_dims() function that has an intuitive axis kwarg. This function takes two parameters. The first is the array of which you want to increase the dimension of and the second is index/indexes of array on which you want to create a new axis.

In [56]:
x = np.zeros((3, 4))
y = np.expand_dims(x, axis=1).shape
print(y)

(3, 1, 4)


Example 2: Simultaneously insert many new axes in the array.

In [57]:
arr = np.arange(5*5).reshape(5,5)
print(arr.shape)
  
newaxes = (0, 3, -1)
arr_5D = np.expand_dims(arr, axis=newaxes)
print(arr_5D.shape)

(5, 5)
(1, 5, 5, 1, 1)


## hsatck() aray

In [59]:
in_arr1 = np.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = np.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays horizontally
out_arr = np.hstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


## Joining NumPy Array

NumPy provides various functions to combine arrays. In this article, we will discuss some of the major ones.

numpy.concatenate
numpy.stack
numpy.block



numpy.block()
In this example, we assembled a block matrix( block_new ) from 4 separate 2-d arrays (block_1,block_2,block_3,block_4 ).

In [ ]:
block_1 = np.array([[1, 1], [1, 1]])
block_2 = np.array([[2, 2, 2], [2, 2, 2]])
block_3 = np.array([[3, 3], [3, 3], [3, 3]])
block_4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]])
  
block_new = np.block([
    [block_1, block_2],
    [block_3, block_4]
])
  
print(block_new)

## Combining a one and a two-dimensional NumPy Array


In [61]:
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)
  
num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)
  
# Combine 1-D and 2-D arrays and display 
# their elements using numpy.nditer() 
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


## Numpy np.ma.concatenate() method

## Numpy dstack() method

Numpy dstack() method
With the help of numpy.dstack() method, we can get the combined array index by index and store like a stack by using numpy.dstack() method.

Syntax : numpy.dstack((array1, array2))

Return : Return combined array index by index.

## Find unique rows in a NumPy array
How to find unique rows in a NumPy array. To find unique rows in a NumPy array we are using numpy.unique() function of NumPy library.

Syntax of np.unique() in Python
Syntax: numpy.unique()

Parameter:

ar: array
return_index: Bool, if True return the indices of the input array
return_inverse: Bool, if True return the indices of the input array
return_counts: Bool, if True return the number of times each unique item appeared in the input array
axis: int or none, defines the axis to operate on

In [62]:
# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
uniqueRows = np.unique(arr2D, return_inverse=True)
                        
 
# print the output result
print('Unique Rows:',
      uniqueRows, sep = '\n')

Unique Rows:
(array([11, 12, 13, 16]), array([0, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 0, 0, 1, 0], dtype=int64))


In [63]:
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
uniqueRows = np.unique(arr2D, return_index=True)
                        
 
# print the output result
print('Unique Rows:',
      uniqueRows, sep = '\n')

Unique Rows:
(array([11, 12, 13, 16]), array([0, 2, 4, 8], dtype=int64))


# Operations on NumPy Array

# Indexing NumPy Array

### Basic Slicing and indexing

In [65]:
#Boolean Indexing
a = np.array([10, 40, 80, 50, 100])
print(a[a>50])

[ 80 100]


# Accessing Data Along Multiple Dimensions Arrays in Python Numpy


NumPy (Numerical Python) is a Python library that comprises of multidimensional arrays and numerous functions to perform various mathematical and logical operations on them. NumPy also consists of various functions to perform linear algebra operations and generate random numbers. NumPy is often used along with packages like SciPy and Matplotlib for technical computing.
An n-dimensional (multidimensional) array has a fixed size and contains items of the same type. the contents of the multidimensional array can be accessed and modified by using indexing and slicing the array as desired. For accessing elements of an array we need to first import the library: 
 

import numpy as np
We can use Integer Indexing to access elements of data. We can also perform Slicing to access sub-sequences of data.
Ex

In [66]:
# 1-dimensional array
array1D = np.array([1, 2, 3, 4, 5])
 
print(array1D)
 
# to access elements using positive
# index
print("\nusing positive index :" +str(array1D[0]))
print("using positive index :" +str(array1D[4]))
 
# negative indexing works in opposite
# direction
print("\nusing negative index :" +str(array1D[-5]))
print("using negative index :" +str(array1D[-1]))

[1 2 3 4 5]

using positive index :1
using positive index :5

using negative index :1
using negative index :5


In [67]:
# 2-dimensional array
array2D = np.array([[93,  95],
                    [84, 100],
                    [99,  87]])
 
print(array2D)
print("shape :" +str(array2D.shape))
 
print("\npositive indexing :" +str(array2D[1, 0]))
print("negative indexing :" +str(array2D[-2, 0]))
 
print("\nslicing using positive indices :" +str(array2D[0:3, 1]))
print("slicing using positive indices :" +str(array2D[:, 1]))
print("slicing using negative indices :" +str(array2D[:, -1]))

[[ 93  95]
 [ 84 100]
 [ 99  87]]
shape :(3, 2)

positive indexing :84
negative indexing :84

slicing using positive indices :[ 95 100  87]
slicing using positive indices :[ 95 100  87]
slicing using negative indices :[ 95 100  87]


In [68]:
# 3-dimensional array
array3D = np.array([[[ 0,  1,  2],
                     [ 3,  4,  5],
                     [ 6,  7,  8]],
  
                    [[ 9, 10, 11],
                     [12, 13, 14],
                     [15, 16, 17]],
 
                    [[18, 19, 20],
                     [21, 22, 23],
                     [24, 25, 26]]])
 
print(array3D)
print("shape :" +str(array3D.shape))
 
print("\naccessing element :" +str(array3D[0, 1, 0]))
print("accessing elements of a row and a column of an array:"
      +str(array3D[:, 1, 0]))
print("accessing sub part of an array :" +str(array3D[1]))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
shape :(3, 3, 3)

accessing element :3
accessing elements of a row and a column of an array:[ 3 12 21]
accessing sub part of an array :[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


# Variations in different Sorting techniques in Python

These are all different types for sorting techniques that behave very differently. Let’s study which technique works how and which one to use.

Let ‘a’ be a numpy array

a.sort()
(i) Sorts the array in-place & returns None
(ii) Return type is None
(iii) Occupies less space. No copy created as it directly sorts the original array
(iv) Faster than sorted(a)

In [69]:
# Numpy array created
a = np.array([9, 3, 1, 7, 4, 3, 6])
  
# unsorted array print
print('Original array:\n', a)
  
# Return type is None
print('Return type:', a.sort())
  
# Sorted array output
print('Original array sorted->', a)

Original array:
 [9 3 1 7 4 3 6]
Return type: None
Original array sorted-> [1 3 3 4 6 7 9]


sorted(a)
(i) Creates a new list from the old & returns the new one, sorted
(ii) Return type is a list
(iii) Occupies more space as copy of original array is created and then sorting is done
(iv) Slower than a.sort()

In [70]:
# Numpy array created
a = np.array([9, 3, 1, 7, 4, 3, 6])
  
# unsorted array print
print('Original array:\n', a)
b = sorted(a)
  
# sorted list returned to b, b type is
# <class 'list'> 
print('New array sorted->', b)
  
# original array no change
print('Original array->', a)

Original array:
 [9 3 1 7 4 3 6]
New array sorted-> [1, 3, 3, 4, 6, 7, 9]
Original array-> [9 3 1 7 4 3 6]


np.argsort(a)
(i) Returns the indices that would sort an array
(ii) Return type is numpy array
(iii) Occupies space as a new array of sorted indices is returned

In [71]:
a = np.array([9, 3, 1, 7, 4, 3, 6])
  
# unsorted array print
print('Original array:\n', a)
  
# Sort array indices
b = np.argsort(a)
print('Sorted indices of original array->', b)
  
# To get sorted array using sorted indices
# c is temp array created of same len as of b
c = np.zeros(len(b), dtype = int)
for i in range(0, len(b)):
    c[i]= a[b[i]]
print('Sorted array->', c)

Original array:
 [9 3 1 7 4 3 6]
Sorted indices of original array-> [2 1 5 4 6 3 0]
Sorted array-> [1 3 3 4 6 7 9]


np.lexsort((b, a))
(i) Perform an indirect sort using a sequence of keys
(ii) Sort by a, then by b
(iii) Return type ndarray of ints Array of indices that sort the keys along the specified axis
(iv) Occupies space as a new array of sorted indices pair wise is returned.

In [75]:
# Numpy array created
a = np.array([9, 3, 1, 3, 4, 3, 6]) # First column
b = np.array([4, 6, 9, 2, 1, 8, 7]) # Second column
print('column a, column b')
for (i, j) in zip(a, b):
    print(i, ' ', j)
  
ind = np.lexsort((b, a)) # Sort by a then by b
print('Sorted indices->', ind)

column a, column b
9   4
3   6
1   9
3   2
4   1
3   8
6   7
Sorted indices-> [2 3 1 5 4 6 0]


## numpy.sort_complex() in Python
numpy.sort_complex() function is used to sort a complex array.It sorts the array by using the real part first, then the imaginary part.

Syntax : numpy.sort_complex(arr)

Parameters :
arr : [array_like] Input array.

Return : [complex ndarray] A sorted complex array.

In [74]:
# input array
in_arr = [2, 8, 7, 5, 9]
print ("Input array : ", in_arr) 
    
out_arr = np.sort_complex(in_arr) 
print ("Output sorted array : ", out_arr)

Input array :  [2, 8, 7, 5, 9]
Output sorted array :  [2.+0.j 5.+0.j 7.+0.j 8.+0.j 9.+0.j]


# Create your own universal function in NumPy

In [76]:
# creating own function
def fxn(val):
  return (val % 2)
 
# adding into numpy
mod_2 = np.frompyfunc(fxn, 1, 1)
 
# creating numpy array
arr = np.arange(1, 11)
print("arr     :", *arr)
 
# using function over numpy array
mod_arr = mod_2(arr)
print("mod_arr :", *mod_arr)

arr     : 1 2 3 4 5 6 7 8 9 10
mod_arr : 1 0 1 0 1 0 1 0 1 0


## Some of the basic universal functions in Numpy are-
 

Trigonometric functions:

In [77]:
# create an array of angles
angles = np.array([0, 30, 45, 60, 90, 180]) 
  
# conversion of degree into radians
# using deg2rad function
radians = np.deg2rad(angles)
  
# sine of angles
print('Sine of angles in the array:')
sine_value = np.sin(radians)
print(np.sin(radians))
  
# inverse sine of sine values
print('Inverse Sine of sine values:')
print(np.rad2deg(np.arcsin(sine_value)))
  
# hyperbolic sine of angles
print('Sine hyperbolic of angles in the array:')
sineh_value = np.sinh(radians)
print(np.sinh(radians))
  
# inverse sine hyperbolic 
print('Inverse Sine hyperbolic:')
print(np.sin(sineh_value)) 
  
# hypot function demonstration
base = 4
height = 3
print('hypotenuse of right triangle is:')
print(np.hypot(base, height))

Sine of angles in the array:
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
Inverse Sine of sine values:
[0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 7.0167093e-15]
Sine hyperbolic of angles in the array:
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]
Inverse Sine hyperbolic:
[ 0.          0.52085606  0.76347126  0.94878485  0.74483916 -0.85086591]
hypotenuse of right triangle is:
5.0


Statistical functions:

In [78]:
# construct a weight array
weight = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45])
  
# minimum and maximum 
print('Minimum and maximum weight of the students: ')
print(np.amin(weight), np.amax(weight))
  
# range of weight i.e. max weight-min weight
print('Range of the weight of the students: ')
print(np.ptp(weight))
  
# percentile
print('Weight below which 70 % student fall: ')
print(np.percentile(weight, 70))
   
# mean 
print('Mean weight of the students: ')
print(np.mean(weight))
  
# median 
print('Median weight of the students: ')
print(np.median(weight))
  
# standard deviation 
print('Standard deviation of weight of the students: ')
print(np.std(weight))
  
# variance 
print('Variance of weight of the students: ')
print(np.var(weight))
  
# average 
print('Average weight of the students: ')
print(np.average(weight))

Minimum and maximum weight of the students: 
45.0 73.25
Range of the weight of the students: 
28.25
Weight below which 70 % student fall: 
55.317
Mean weight of the students: 
54.3225
Median weight of the students: 
51.6
Standard deviation of weight of the students: 
8.052773978574091
Variance of weight of the students: 
64.84716875
Average weight of the students: 
54.3225


Bit-twiddling functions:
These functions accept integer values as input arguments and perform bitwise operations on binary representations of those integers.

In [79]:
# construct an array of even and odd numbers
even = np.array([0, 2, 4, 6, 8, 16, 32])
odd = np.array([1, 3, 5, 7, 9, 17, 33])
  
# bitwise_and
print('bitwise_and of two arrays: ')
print(np.bitwise_and(even, odd))
  
# bitwise_or
print('bitwise_or of two arrays: ')
print(np.bitwise_or(even, odd))
  
# bitwise_xor
print('bitwise_xor of two arrays: ')
print(np.bitwise_xor(even, odd))
   
# invert or not
print('inversion of even no. array: ')
print(np.invert(even))
  
# left_shift 
print('left_shift of even no. array: ')
print(np.left_shift(even, 1))
  
# right_shift 
print('right_shift of even no. array: ')
print(np.right_shift(even, 1))

bitwise_and of two arrays: 
[ 0  2  4  6  8 16 32]
bitwise_or of two arrays: 
[ 1  3  5  7  9 17 33]
bitwise_xor of two arrays: 
[1 1 1 1 1 1 1]
inversion of even no. array: 
[ -1  -3  -5  -7  -9 -17 -33]
left_shift of even no. array: 
[ 0  4  8 12 16 32 64]
right_shift of even no. array: 
[ 0  1  2  3  4  8 16]
